# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de5ce7130e3d26880059a42d484da9907eb7d5d2215b7625ed327fc4b4d0b0bb6e2d9c64e54cc65ef75ca02cbf106cbf9de3e3dd7d17c8478908ee4a8af18210

test:
  secret_key_base: 5be36b04edc26c35fd68279c22c5cc376f3ff2ea8e05bdc0588cf0a19f7810f439574fd114fa0667aa644803c152f20cb1e083de6a1bbccf6a11e2a2c71e5d7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
